services:
    webserver:
        container_name: verivote-webserver
        build:
            args:
                APP_ENV: "production"
            dockerfile: Dockerfile
        ports:
            - "127.0.0.1:3001:3000"
        restart: unless-stopped
        depends_on:
            database:
                condition: service_started

    database:
        container_name: verivote-database
        build:
            dockerfile: ./database/Dockerfile
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        ports:
            - "127.0.0.1:3003:27017"
        restart: unless-stopped
        volumes:
            - ./database/init.d:/docker-entrypoint-initdb.d:ro
            - ./database/data/db:/data/db
            - ./database/data/log:/var/log/mongodb