services:
    frontend:
        container_name: verivote-webserver
        build:
            dockerfile: Dockerfile
        expose:
            - "3000"
        ports:
            - "127.0.0.1:3000:3000"
        restart: unless-stopped
        depends_on:
            database:
                condition: service_started

    database:
        container_name: verivote-database
        build:
            dockerfile: ./database/Dockerfile
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        expose:
            - "27017"
        ports:
            - "127.0.0.1:3003:27017"
        restart: unless-stopped
        volumes:
            - ./database/init.d:/docker-entrypoint-initdb.d:ro
            - ./database/data/db:/data/db
            - ./database/data/log:/var/log/mongodb

    keycloak:
        image: quay.io/keycloak/keycloak:24.0.1
        container_name: verivote-keycloak
        ports:
            - "8080:8080"
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        volumes:
            - ./keycloak-config:/opt/keycloak/data/import
        command: start-dev --import-realm

    playwright:
        image: mcr.microsoft.com/playwright:v1.52.0-noble
        container_name: verivote-playwright
        entrypoint: [ "npx", "playwright", "test" ]
        volumes:
            - .:/tests/e2e
        working_dir: /tests/e2e
        environment:
            - DISPLAY=${DISPLAY}
            - TZ=UTC
        network_mode: "host"
        depends_on: [ ]
        ipc: host
        privileged: true
        devices:
            - /dev/dri
        shm_size: 1gb