version: "3.8"
services:
    frontend:
        container_name: verivote-frontend
        image: verivote-frontend
        build:
            dockerfile: frontend.Dockerfile
        expose:
            - "3000"
        ports:
            - "127.0.0.1:3001:3000"