services:
    frontend:
        container_name: verivote-frontend
        image: verivote-frontend
        build:
            dockerfile: Dockerfile
        expose:
            - "3000"
        ports:
            - "127.0.0.1:3001:3000"
        restart: unless-stopped
        depends_on:
            backend:
                condition: service_started

    backend:
        container_name: verivote-backend
        restart: unless-stopped
        build:
            dockerfile: ./backend/Dockerfile
        expose:
            - "4000"
        ports:
            - "127.0.0.1:3002:4000"
        depends_on:
            database:
                condition: service_started

    database:
        container_name: verivote-database
        image: verivote-database
        build:
            dockerfile: ./database/Dockerfile
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        expose:
            - "27017"
        ports:
            - "127.0.0.1:3003:27017"
        restart: unless-stopped
        volumes:
            - ./database/init.d:/docker-entrypoint-initdb.d:ro
            - ./database/data/db:/data/db
            - ./database/data/log:/var/log/mongodb