openapi: 3.0.3
info:
  title: Verivote API
  description: |-
    Verivote is a free open source website that offers a hands-on approach for educating people about
    alternative voting systems. You are welcome to deploy this website yourself or fork it and make it your
    own. It comes with a default backend written in Go but you can replace that backend with your own by
    matching this API specification
  version: 1.0.0
servers:
  - url: "http://localhost:4000/api"
paths:
  /poll:
    post:
      summary: Create a new poll
      description: This endpoint creates a new poll and returns a `201 Created` status with a `Location` header on success.
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Title of the poll
                  example: "Favorite programming language?"
                  maxLength: 200
                votingMethod:
                  type: string
                  description: The type of voting method to use for the poll
                  example: "Instant-Runoff"
                date:
                  type: string
                  description: An RFC3339 datetime string indicating the closing date of the poll
                  example: "2024-10-16T12:59:00+02:00"
                options[]:
                  type: array
                  description: List of poll options
                  items:
                    type: string
                  example: ["Python", "JavaScript", "Go"]
                majority:
                  type: string
                  description: If set to any value a candidate needs a majority to win
                  example: "on"
              required:
                - name
                - votingMethod
                - date
                - options[]
      responses:
        '201':
          description: Poll created successfully
          headers:
            Location:
              description: The URL of the newly created poll
              schema:
                type: string
                format: uri
        '400':
          description: Bad request, the form data is incorrect
        '401':
          description: Unauthorized, the user is not allowed to create polls
        '500':
          description: Internal server error, if env vars aren't set on the server
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: next-auth.session-token
      description: The encrypted JWT generated by Next.js
 