name: Deploy to VPS

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        env:
          MONGO_ROOT_USER: ${{ secrets.MONGO_ROOT_USER }}
          MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          envs: MONGO_ROOT_USER,MONGO_ROOT_PASSWORD
          script: |
            cd /home/${{ secrets.VPS_USER }}/git/verivote
            git checkout main
            git pull
            touch .env.local
            echo "${{ secrets.ENV }}" > .env.local
            sed "s/__VERIVOTE_PASSWORD__/${{ secrets.MONGO_USER_PASSWORD }}/g" database/init.d/mongo-init.template.js > database/init.d/mongo-init.js
            docker compose -f compose.production.yml up -d --build