name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm run unit-tests